// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
}
export {}
